### ISSUE TITLE
Documentation: gimnl

### ISSUE THREAD

**Issue by cmaimone** [hknd23/idcempy#11]
https://idcempy.readthedocs.io/en/latest/gimnl_tutorial.html - there are some typos (e.g. "testcode") and empty boxes on this page.  

Also consider rewording a bit to make this more clearly an example that happens to use the data than it being about the data/model.  From the title of the page, I expect to learn what's in this module and how to use it, but the content of the page jumps into a specific analysis example -- it felt like it was more about the data being modeled than about the package module itself, with the data being an example of how to use the software.  

Remember that this is documentation about the package -- users are coming to this page to learn how to use your software (I got a bit lost approaching the page with this goal in mind).  Additional information about the statistical method can be included to support explanations of how to use the software correctly, but keep the focus on the software.

**Comment by hknd23** [comment]
This is a great point.  We addressed it by reframing the structure of the documentation files to keep the focus on the software and provided more detailed explanations on how to utilize the software. Further, users can find a more detailed explanation of the statistical methods including additional information about the statistical methods employed by reading the details provided on the README.

**Comment by cmaimone** [comment]
There are still some formatting issues/typos in https://idcempy.readthedocs.io/en/latest/idcempy_tutorial.html#generalized-inflated-multinomial-logit-gimnl-model

`mnl_2004vote = gimnl.mnlmod(data, x, y, method = )`

Spaces before the import lines (this occurs elsewhere too)
```
 import pandas as pd
 import urllib
 from idcempy import gimnl
```

Formatting around: The flexibility of gimnl.gimnlmod allows users to customize the baseline and inflated categories. Users can employ the argument `inflatecat() with 

Indentation of The first element of the list is the baseline/reference category.

Give another editing pass to this section, and across the documentation in general

**Comment by hknd23** [comment]
Following your advice, we have conducted another round of careful checks and edits of the section that you mention and the documentation in general. To this end, we have first corrected all the typos and mistakes that you have identified above. Next, we have addressed and edited formatting issues and typos across the entire documentation as thoroughly as possible.
