### ISSUE TITLE
Documentation: more details on parameters

### ISSUE THREAD

**Issue by cmaimone** [hknd23/idcempy#15]
API documentation could use some additional details in the parameter descriptions.  For example, 

> method – method for optimization, default ‘BFGS’

Are there alternatives that could be specified?

> reference – order of categories

This gives me no information as to what I'm actually supposed to provide.  

> y – Dependent Variable. Variable needs to be in factor form, with a number from 0-2 representing each category.

Is this the name of the variable, or a Series, or a list?  "factor" doesn't have specific meaning in Python - does the variable need to contain integer values?  Strings?

These are examples, but there are other unclear descriptions

**Comment by hknd23** [comment]
Following your suggestion, we also added more detail to other places with unclear descriptions. For instance, in our GiMNL documentation, we included more information on how to specify the inflated category with “inflatecat” and how the combination of “reference” and “inflatecat” can be employed.
