### ISSUE TITLE
Paper: split statement of need section into more than one paragraph

### ISSUE THREAD

**Issue by cmaimone** [hknd23/idcempy#20]
Statement of need section of the paper could use some paragraph divisions.

**Comment by hknd23** [comment]
Thank you for this constructive suggestion. We have divided the “Statement of Need” section into two short paragraphs in the revised paper. The first paragraph (starts with the words. “Although our IDCeMPy package also fits…”) in this revised section is 13 lines long. The second paragraph (begins with “The functions in IDCeMPy use quasi-Newton…”) is 11 lines long.
