### ISSUE TITLE
Paper: "standard libraries"

### ISSUE THREAD

**Issue by cmaimone** [hknd23/idcempy#5]
In the paper, around line 86, it says 

> [Python](https://www.python.org/) standard libraries such as `NumPy`, `pandas`, and `SciPy` 

"standard library" has a specific meaning though: https://docs.python.org/3/library/ -- rephrase to something like "commonly-used" or "well-established"

**Comment by hknd23** [comment]
We agree with your claim and have thus dropped the term “standard library” as well as the sentence (since it is not required) that included this term in the revised paper.
