### ISSUE TITLE
Documentation: organization

### ISSUE THREAD

**Issue by cmaimone** [hknd23/idcempy#8]
Going to the main page of the readthedocs documentation, I was confused about what each linked page was.  I generally expect to see something like:
- Installation
- Quick start (if relevant)
- Examples/tutorials
- API (just function documentation) -- this you have

I was confused because there's a dedicated bullet for gimnl module, but not zmiopc - the latter is only listed under API.  

In the first section:
Data Description - this is not a usual entry in a Python package documentation, so some clarity would help -- this is citation information and description for the datasets you use in the examples?  If so, this should probably be downplayed and not be the second bullet in your documentation.

Are these all examples of how to use the package?
Estimation of Zero-inflated and Middle-inflated Ordered Probit Models Without Correlated Errors
Estimation of Zero-inflated and Middle-inflated Ordered Probit Models “With” Correlated Errors
Estimating the OP Model
The Vuong Test
Split Equtation Predicted Probablities 
Outcome Equation Predicted Probabilities

Side note: spelling errors in Split Equtation Predicted Probablities 

Overall, it would be helpful if it was clearer on the main page what everything is, and that there's consistency.

**Comment by hknd23** [comment]
We certainly agree with this point. Hence, as mentioned in our earlier responses to your suggestions, we updated and reorganized all the documentation files in our IDCeMPy package. Doing so undoubtedly helped us to make the exposition not just as consistent as possible but also more lucid.
